name: CI
on:
  pull_request:
  push: 
    branches: [master]

jobs:
  unit-test:
    name: Unit Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cabal: ["3.0"]
        ghc: ["8.8.4"]
    env:
      CONFIG: "--enable-tests --enable-benchmarks"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-haskell@v1
        id: setup-haskell-cabal
        with:
          ghc-version: ${{matrix.ghc}}
          cabal-version: ${{matrix.cabal}}
      - run: cabal v2-update
      - run: cabal v2-freeze $CONFIG
      - uses: actions/cache@v2
        with:
          path: |
            ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
            dist-newstyle
          key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.ghc }}-
      - run: cabal v2-test
